version: '3'
services:
  api:
    build: ./
    ports:
      - 5002:5002
    volumes:
      - ./:/go/src/github.com/cryplio/rest-api
    depends_on:
      - database
    env_file:
      - ./config/api.env
    container_name: cryplio_api
    entrypoint: /go/src/github.com/cryplio/rest-api/tools/wait-for-database.sh

  database:
    image: postgres:10.1
    ports:
      - "5432"
    env_file:
      - ./config/database.env
    container_name: cryplio_api_postgres