# Group Users


:[get featured](get_featured.handler.apib)

## User [/users/{id}]

+ Parameters
    + id (string) - ID of the targeted user

:[Item Get](get.handler.apib)

:[Item Patch](update.handler.apib)

:[Item Delete](delete.handler.apib)

## User Collection [/users{?page,per_page,sort}]

:[Add](add.handler.apib)
:[List](list.handler.apib)
