FORMAT: 1A
HOST: http://api-orchid.crypl.io/

# Cryplio REST API

API used to run cryplio

:[Group User](../src/modules/users/users.apib)

:[Group Session](../src/modules/sessions/sessions.apib)


# Data Structure

:[User](../src/modules/users/users.payload.apib)

## Session

+ token (required, string)
+ user_id (required, string)

## DefaultError

+ error : not a valid uuid (required, string) - Reason of the error
+ field : id (string) - Name of the field that failed

## Error401

+ error : unauthorized (required, string)

## Error403

+ error : forbiden (required, string)

## Error404

+ error : not found (required, string)

## Error500

+ error : something went wrong (required, string)
