# Group Portfolios

## Portfolio [/portfolios/{id}]

+ Parameters
    + id (string) - ID of the targeted user


:[Item Update](http/handlers/update.handler.apib)

:[Item Delete](http/handlers/delete.handler.apib)

## Pportfolio Collection [/portfolios{?page,per_page,sort}]

:[Add](http/handlers/add.handler.apib)
:[List](http/handlers/list.handler.apib)
