# Group Portfolios

## Portfolio [/portfolios/{id}]

+ Parameters
    + id (string) - ID of the targeted user


:[Item Upade(update.handler.apib)

:[Item Delete](delete.handler.apib)

## Pportfolio Collection [/portfolios{?page,per_page,sort}]

:[Add](add.handler.apib)
:[List](list.handler.apib)
